### ISSUE TITLE
Include mumble-web?

### ISSUE THREAD

**Issue by poVoq** [DuckBoss/Mumimo#19]
Would be awesome if this could include a working web-client for Mumble like mumble-web: https://github.com/Johni0702/mumble-web

Thanks!

**Comment by DuckBoss** [comment]
Oh that's interesting, I'll look into it and see what I can do!
This rework is still in early phases, but I'll add this as an investigation task on the Jira board, thanks!

**Comment by DuckBoss** [comment]
After further investigation, I don't think it would be feasible to add a full web-client like this for Mumimo.
However, I plan on expanding the client features available in the web interface to include some of the features of this client (like mute/deafen/moving channels, and admin functionality like kick/ban users)
